### ISSUE TITLE
[bug]: `exchange_rate`: it does not work

### ISSUE THREAD

**Issue by diver9989** [unytics/bigfunctions#130]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

![image](https://github.com/unytics/bigfunctions/assets/122979159/b8ce7502-8615-4dfd-8c38-4700d37caf52)

seems like not working ;(

**Comment by unytics** [comment]
Hi 👋  @diver9989,

Thanks a lot for opening this issue. 

Seems like https://exchangerate.host which is used in this function is not free anymore.

Let me find an alternative. 

If you have one, don't hesitate to tell me

**Comment by unytics** [comment]
I found two open-source packages:

1. https://github.com/MicroPyramid/forex-python : the data is from European Central Bank. It seems great but only covers 31 currencies instead of 169 currencies that were supported by exchangerate.host. https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
2. https://github.com/fawazahmed0/currency-api/ : 1500 github stars. Much more countries.

What do you think?

**Comment by unytics** [comment]
Finally, I changed the source to use Yahoo Finance. I re-deployed the function. 
Here is the new code: https://github.com/unytics/bigfunctions/blob/main/bigfunctions/exchange_rate.yaml#L33

To me, it works. 
Please re-open an issue if you encounter any other problem.

Thanks again for creating this ticket!
